### ISSUE TITLE
Any plans for i18n text support?

### ISSUE THREAD

**Issue by preet** [google/flatui#3]
From a quick glance I see that text shaping has the following defaults with HarfBuzz:

    hb_buffer_set_direction(harfbuzz_buf_, HB_DIRECTION_LTR);
    hb_buffer_set_script(harfbuzz_buf_, HB_SCRIPT_LATIN);
    hb_buffer_set_language(harfbuzz_buf_, hb_language_from_string(text, length));

There's a TODO to make these configurable but are there any plans for more robust i18n support such as BiDi, script detection etc?

**Comment by hak** [comment]
In master, now it supports SetTextLocale() API.
With the API, for instance SetTextLocale('ar'), Label/Edit widget support RTL languages.

Items not supported yet are:
- Font fallback when a font doesn't include some glyphs.
  I'm working on the feature.
- Unicode BiDi control characters.
  http://www.i18nguy.com/markup/right-to-left.html
- Switching other layout directions (e.g. Group layout direction)
  Not sure if it's necessary. Any feedback is appreciated.
- Script detection.
  I'm leaning toward not to have the feature since,
  - Using compact language detector2 would add additional MB for a library footprint.
   https://code.google.com/p/cld2/
 Also any feedback is appreciated.

**Comment by preet** [comment]
Setting locale seems like a good solution for single language support, but once you mix in multiple languages at once you might need BiDi and script direction to pass information along to Harfbuzz when you do shaping. I've been looking for a small lib to handle i18n mixed text rendering for me and thought I'd push the responsibility on to you :p

If multiple languages in text isn't worth supporting, I think setting locale is good enough. If there are plans to support it, then you need fallback (I can't see fallback mattering too much if you stick to a single language as most fonts are designed to support at least one language unless Im missing something), BiDi and script detection.

I've tried to do something similar to what flatui is doing for text rendering and ended up using harfbuzz+libunibreak+ICU (for bidi and script detection)... ICU is a huge dep. There might be other independent BiDi libraries with a compatible license too though (like https://github.com/mta452/SheenBidi, untested)

My specific use case is rendering map labels which may contain mixed i18n text. This is pretty niche, so whether or not mixed i18n text is in the scope of this project is up to you folks.

**Comment by hak** [comment]
Locale support is added in /develop branch.
